# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{call_stack}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2009-10-19}
  s.default_executable = %q{call_stack}
  s.description = %q{call_stack is a ruby gem to display method call stack in browser.}
  s.email = %q{flyerhzm@gmail.com}
  s.executables = ["call_stack"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/call_stack.rb",
     "lib/call_stack/controller.rb",
     "lib/call_stack/server.rb",
     "lib/call_stack/static/javascripts/jquery-1.3.2.min.js",
     "lib/call_stack/static/stylesheets/call_stack.css",
     "lib/call_stack/templates/index.erb",
     "lib/call_stack/unroller.rb",
     "lib/call_stack/unroller_server.rb",
     "lib/colored/colored.rb",
     "lib/example.rb",
     "spec/colored_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{call_stack is a ruby gem to display method call stack in browser.}
  s.test_files = [
    "spec/colored_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
