# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monitor}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2009-10-23}
  s.description = %q{monitor is a ruby gem to monitor method call stacks in browser.}
  s.email = %q{flyerhzm@gmail.com}
  s.executables = ["monitor", "monitor"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/monitor",
     "lib/colored/colored.rb",
     "lib/example.rb",
     "lib/monitor.rb",
     "lib/monitor/command.rb",
     "lib/monitor/controller.rb",
     "lib/monitor/server.rb",
     "lib/monitor/unroller.rb",
     "lib/monitor/unroller_server.rb",
     "monitor.gemspec",
     "public/images/icons.png",
     "public/index.html",
     "public/javascripts/jquery-1.3.2.min.js",
     "public/javascripts/monitor.js",
     "public/stylesheets/monitor.css",
     "spec/colored_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{monitor is a ruby gem to monitor method call stacks in browser.}
  s.test_files = [
    "spec/colored_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<unroller>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<unroller>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<unroller>, [">= 0"])
  end
end
